### ISSUE TITLE
I made a new program using your tutorial and it doesnt seem to work!

### ISSUE THREAD

**Issue by neutralboy** [Akuli/python-tutorial#3]
The program is meant to function as a diary:
The file *usr.txt* has line 3 as "defusr" and line 4 as "123" 
The code is located on [http://dpaste.com/1Q0BQGC.txt](url) as GitHub does not seem to recognize proper indentation.

**Comment by Akuli** [comment]
Yeah, you need to add 4 spaces before each line if you paste code in GitHub.

Your code is pretty hard to read right now. See [Good and bad variable names](https://github.com/Akuli/python-tutorial/blob/master/basics/variables.md#good-and-bad-variable-names) (it also applies to functions, so `create_new_user` would be good). The worst problem is that right now I have no idea what `f01`, `x01` and other variables do. So fix the variable names and make a new paste, I'll try to help you then :)

**Comment by Akuli** [comment]
Looking at your code a bit more the file stuff has things like `read(1)` and `writelines(...)` and `close()` that I don't use anywhere in the tutorial. The tutorial also has [a chapter about files](https://github.com/Akuli/python-tutorial/blob/master/basics/files.md) with easier ways to use files, so you may want to use that instead.

Another problem is that you're comparing strings with numbers. See the last example [here](https://github.com/Akuli/python-tutorial/blob/master/basics/loops.md#examples).

By the way, it's normal to have problems with your code :) Most of the programs I write don't work on the first try either, and that's what the error messages are for.

**Comment by neutralboy** [comment]
Thank you very much @Akuli  for your useful insight I have made all the changes required and also realized that many lines of code were useless.... here's an edited version
[Here's the code!](http://dpaste.com/15FVPSQ.txt)

**Comment by Akuli** [comment]
Great :) Now it's easier to find problems:

    if usrname == usr_file.read(3):

`file.read(3)` doesn't read the third line from the file. It means "read next 3 characters from the file". Usually it's best to use methods like `readline()` or just for loop over the file. See [my file chapter](https://github.com/Akuli/python-tutorial/blob/master/basics/files.md#reading-from-files).

    usr_file = open("usrdiary.txt", "w")
    print("Your diary has the following content: \n",usr_file)

Here you're confusing the file object from `open()` with its content. If you want to print the whole content of a file, do something like `print(file.read())`. You also need `"r"` instead of `"w"`.

I recommend coming to [this free help chat](http://webchat.freenode.net/?channels=%23%23learnpython). You don't need to register or anything, just click the link, choose a name and you're ready to go. I'm Akuli there too, so hopefully we can talk there and get things to work :) There are also many other skilled people ready to help you if I'm not there.

**Comment by Akuli** [comment]
You haven't said anything to me in over a year, so I guess you are not working on this program anymore.
